apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-3
spec:
  dataFrom:
  - find:
      path: /example-1/stage/
      name:
        regexp: '.*'
    rewrite:
    - regexp:
        source: "/example-1/stage/(.*)"
        target: "$1"
