repo:
- changed-files:
  - any-glob-to-any-file: '*'

enigma:
- changed-files:
  - any-glob-to-any-file: ['argocd/**/*', 'charts/**/*', 'infrastructure/**/*' ]


kevlar:
- changed-files:
  - any-glob-to-any-file: projects/kevlar/**/*

marvel:
- changed-files:
  - any-glob-to-any-file: projects/marvel/**/*

propforce:
- changed-files:
  - any-glob-to-any-file: projects/propforce/**/*

zameen:
- changed-files:
  - any-glob-to-any-file: projects/zameen/**/*

live:
- changed-files:
  - any-glob-to-any-file: ['projects/**/live/**', 'projects/**/base/**']

github:
- changed-files:
  - any-glob-to-any-file: .github/**/*

docs:
- changed-files:
  - any-glob-to-any-file: docs/*

non-live:
- all:
  - changed-files:
    - any-glob-to-any-file: 'projects/**/*'
    - all-globs-to-all-files: ['!projects/**/live/**', '!.github/**/*' ]
