- name: 'enigma'
  color: '0052CC'
- name: 'kevlar'
  color: '00484F'
- name: 'marvel'
  color: 'D93F0B'
- name: 'propforce'
  color: 'BDFD70'
- name: 'zameen'
  color: '0E8A16'
- name: 'live'
  color: 'B60205'
- name: 'non-live'
  color: 'C5DEF5'
- name: 'github'
  color: '474848'
- name: 'docs'
  color: 'dee2e6'
