name: "Pull Request Labeler"
on:
  pull_request
jobs:
  triage:
    runs-on: enigma-scale-set
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
