name: PR Enforcer

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  enforce:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Run PR Enforcer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_TOKEN: ${{ secrets.ORG_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          ORG_NAME: "enigma-ruqaish"
        run: |
          chmod +x .github/workflows/pr-enforcer.sh
          .github/workflows/pr-enforcer.sh
