name: PR Enforcer

on:
  pull_request:
    branches: [ "master" ]
    types: ["opened", "synchronize", "reopened", "labeled", "unlabeled", "edited"]

permissions:
  contents: read
  pull-requests: write

jobs:
  enforce:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Verify, Enforce & Auto Approve
        env:
          ORG_TOKEN: ${{ secrets.ORG_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Save the full GitHub event context
          cat << OBJECT > github.json
          ${{ toJson(github) }}
          OBJECT

          # Run the enforcement logic
          . .github/workflows/pr-enforcer.sh
