name: PR enforcer

on:
  pull_request:
    branches: [ "master" ]
    types: ["opened", "synchronize", "reopened", "labeled", "unlabeled", "edited"]

permissions:
  contents: read
  pull-requests: write

jobs:
  enforce:
    runs-on: enigma-scale-set

    steps:
    - uses: actions/checkout@v3
    - name: Verify, Enforce & Approve
      run: |
        cat << OBJECT > github.json
        ${{ toJson(github) }}
        OBJECT
        . .github/workflows/pr-enforcer.sh

        export ORG_TOKEN=${{ secrets.ORG_TOKEN }}
        skip_check && exit 0 || true

        install_yq
        fetch
        verify_diff

        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        update_pr_title

        export ORG_TOKEN=${{ secrets.ORG_TOKEN }}
        auto_approve
