name: PR Enforcer

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled, edited]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  enforce:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Verify, Enforce & Auto Approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ORG_TOKEN: ${{ secrets.ORG_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          ORG_NAME: ${{ github.repository_owner }}
        run: |
          chmod +x .github/workflows/pr-enforcer.sh

          # Save GitHub event for jq access
          cat << OBJECT > github.json
          ${{ toJson(github.event) }}
          OBJECT

          .github/workflows/pr-enforcer.sh
